[0m15:15:25.926723 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1070c2a50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126dbb10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x1126dbd90>]}


============================== 15:15:25.946916 | 143c66d3-4e00-41bc-a59e-05c51d754d15 ==============================
[0m15:15:25.946916 [info ] [MainThread]: Running with dbt=1.9.4
[0m15:15:25.947194 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': '/Users/hemchheda/.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'invocation_command': 'dbt ls', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'introspect': 'True', 'send_anonymous_usage_stats': 'True'}
[0m15:15:25.947458 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path /Users/hemchheda/hem/airflow-dbt-cosmos/cosmos-demo/dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m15:15:25.963775 [debug] [MainThread]: Resource report: {"command_name": "list", "command_success": false, "command_wall_clock_time": 0.08692558, "process_in_blocks": "0", "process_kernel_time": 0.345224, "process_mem_max_rss": "149536768", "process_out_blocks": "0", "process_user_time": 1.366003}
[0m15:15:25.964037 [debug] [MainThread]: Command `dbt ls` failed at 15:15:25.963993 after 0.09 seconds
[0m15:15:25.964222 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112744180>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x11259b650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x112535bf0>]}
[0m15:15:25.964392 [debug] [MainThread]: Flushing usage events
[0m15:15:26.996247 [debug] [MainThread]: An error was encountered while trying to flush usage events
